from langchain.prompts import (
    ChatPromptTemplate,
    MessagesPlaceholder,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate
)
import os
from langchain.chains import ConversationChain
from langchain.chat_models import ChatOpenAI
from langchain.memory import ConversationBufferMemory
import openai

api_key = os.environ.get('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')
openai.api_key = api_key
prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template('''
The following is a conversation between a human and an AI. The AI is interviewer who ask questions and user have to reply it.Our main goal is to judge communication skill of user so AI generated questions should be related to that.  AI ask question then user reply then AI ask new question. It should be dynamic means next question should depend on answer of previous question but after interview AI will provide suggestion based on this interview. Interview start with AI'''),
    MessagesPlaceholder(variable_name="history"),
    HumanMessagePromptTemplate.from_template("{input}")
])


def create_teacher_prompt():
    prompt_teacher = ChatPromptTemplate.from_messages([
        SystemMessagePromptTemplate.from_template(f'''
    The following is a conversation between a human and an AI. where human is student and AI is teacher for same school
    I want AI to work as teacher. After this conversation ai will provide suggestion that can improve user's communication skill. during interview AI must have to work as teacher so whenever student ask any question like he want syllabus for xyz subject so AI (teacher) have to answer that question. dummy data is totally okay our goal is judge student's communication skill. and do not generate data for student and one more thing please reply as teacher with normal(small) sentence
    AI: 

    '''),  MessagesPlaceholder(variable_name="history"),
        HumanMessagePromptTemplate.from_template("{input}")])
    return prompt_teacher

phone_prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template('''The following is a conversation between a human and an AI.AI is user's relative or friends where user want to improve communication skill specially during attending telephone call
    After this conversation ai will provide suggestion that can improve user's communication skill. during interview AI must have to work as user's friend or relative  so whenever user ask any question AI must have to answer that question. dummy data is totally okay our goal is judge student's communication skill. 
  
    AI will not generate text for user's part. it have to wait for use's answer before generating new text and remember ai is either friend or relative of user and it is depend on user's input text. 
    AI:
    
    '''),
      MessagesPlaceholder(variable_name="history"),
        HumanMessagePromptTemplate.from_template("{input}")])


career = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template('''The following is a conversation between a human and an AI. AI supposed to ask questions related to behaviour, IQ or EQ. our main goal is to provide any suggestion or correction related to career for user based on conversation of ai and student. AI will ask question then student will reply then ai ask new question related to behaviour, IQ or EQ and it may be related to answer of previous question.
and one more thing question generated by ai should be small and easy(not hard)
start interview and ask question 

ai:
'''),
    MessagesPlaceholder(variable_name="history"),
    HumanMessagePromptTemplate.from_template("{input}")
])

def create_model():
    llm = ChatOpenAI(temperature=0.9, openai_api_key='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')
    memory = ConversationBufferMemory(return_messages=True)
    conversation = ConversationChain(memory=memory, prompt=prompt, llm=llm)
    return conversation


def create_teacher_model(prompt):
    llm = ChatOpenAI(temperature=0.9, openai_api_key='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')
    memory = ConversationBufferMemory(return_messages=True)
    conversation = ConversationChain(memory=memory, prompt=prompt, llm=llm)
    return conversation


def create_phone_model():
    llm = ChatOpenAI(temperature=0.9, openai_api_key='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')
    memory = ConversationBufferMemory(return_messages=True)
    conversation = ConversationChain(memory=memory, prompt=phone_prompt, llm=llm)
    return conversation   

def create_career_model():
    llm = ChatOpenAI(temperature=0.9, openai_api_key='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')
    memory = ConversationBufferMemory(return_messages=True)
    conversation = ConversationChain(memory=memory, prompt=career, llm=llm)
    return conversation   
# prompt = create_teacher_prompt("hello ma'am, I am neel jotaniya")
# conversation = create_teacher_model(prompt)
def chat(input, conversation):
    return conversation.predict(input=input)









# print(correct_grammar("My nam is Neel.."))